apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: trust-manager-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trust-manager-cyngus-labs-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: trust-manager-cyngus-labs-ca
  secretName: trust-manager-cyngus-labs-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: trust-manager-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cygnus-labs-bundle
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: "trust-manager-cygnus-labs-ca-secret"
      key: "tls.crt"
  target:
    configMap:
      key: "trust-bundle.pem"
