# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
keys:
  - &primary age1wg93d32ww6l3euq2xcrufdjly24avfzm8kt0svkpl2ardgs94spqktmhjv
  - &work age1mx2c3rnt6cnqqe776ux28k4pkctqp0f0ncmal9pqr2k3uz9qsufqg0yzcf
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *primary
      - *work