repositories:
  # Load Balancers
  - name: jetstack 
    url: https://charts.jetstack.io  
  

releases: 
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.15.3
    timeout: 600
    labels:
      app: cert-manager
      tier: infrastructure
    values:
      - values-cert-manager.yaml

  - name: cert-manager-cloudflare
    namespace: cert-manager
    chart: ./chart
    version: 1.0.0
    labels:
      app: cert-manager
      tier: infrastructure  
    secrets:
      - secrets.yaml      
    # hooks:  
    #   - events: ["postsync"]
    #     showlogs: true
    #     command: kubectl
    #     args:
    #       - apply
    #       - -f
    #       - cert-manager-issuers.yaml    