apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      hostNetwork: true
      containers:
      - name: traefik
        image: traefik:v2.9
        ports:
        - name: web
          containerPort: 10080
        - name: websecure
          containerPort: 10443
        args:
        - --entrypoints.web.address=:10080
        - --entrypoints.websecure.address=:10443
        - --providers.kubernetescrd
