apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cygnus-labs.com
  namespace: traefik
spec:
  secretName: wildcard-cygnus-labs.com-tls
  dnsNames:
    - "*.services.production.cygnus-labs.com"
  issuerRef:
    name: cloudflare
    kind: Issuer  
 