
config:
  resources:
    - apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default-pool
        namespace: metallb-system
      spec:
        addresses:
          #- 127.0.0.1/32
          - 102.135.163.95/32
    - apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: default
        namespace: metallb-system
    # - apiVersion: metallb.io/v1beta1
    #   kind: IPAddressPool
    #   metadata:
    #     name: application-services
    #     namespace: metallb-system
    #   spec:
    #     addresses:
    #       - 102.135.163.95/32
    #       # - 172.1.1.2-172.1.1.255
    # - apiVersion: metallb.io/v1beta1
    #   kind: L2Advertisement
    #   metadata:
    #     name: application-services
    #     namespace: metallb-system
    #   spec:
    #     ipAddressPools:
    #       - application-services