repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik  

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    atomic: true
    labels:
      app: traefik
      tier: infrastructure
    values:
      - values-traefik.yaml


  - name: whoami
    namespace: whoami
    chart: ./charts/whoami
    atomic: true
    labels:
      app: whoami
      tier: services
    needs:
      - traefik/traefik    
  